### ISSUE TITLE
Cordova ios crashes on eye icon click

### ISSUE THREAD

**Issue by sreekar89** [findmate/cordova-plugin-jitsi-meet#6]
ref: https://github.com/jitsi/jitsi-meet/issues/5561 is fixed in sdk

Please update sdk.

Current ERROR:
  2020-05-11 13:49:09.346 [error][tid:main][RCTStatusBarManager.m:123] RCTStatusBarManager module requires that the                 UIViewControllerBasedStatusBarAppearance key in the Info.plist is set to NO
2020-05-11 13:49:09.346522+0530 WeInvite[1505:484072] RCTStatusBarManager module requires that the                 UIViewControllerBasedStatusBarAppearance key in the Info.plist is set to NO
2020-05-11 13:49:09.346596+0530 WeInvite[1505:484790] *** Assertion failure in -[FBSSerialQueue assertOnQueue], /BuildRoot/Library/Caches/com.apple.xbs/Sources/FrontBoardServices/FrontBoard-626.4.1/FrontBoardServices/FBSSerialQueue.m:98
2020-05-11 13:49:09.348 [fatal][tid:com.facebook.react.ProximityQueue] Exception 'threading violation: expected the main thread' was thrown while invoking setEnabled on target Proximity with params (
    1
)
2020-05-11 13:49:09.348446+0530 WeInvite[1505:484790] Exception 'threading violation: expected the main thread' was thrown while invoking setEnabled on target Proximity with params (
    1
)
2020-05-11 13:49:09.349071+0530 WeInvite[1505:484790] *** Terminating app due to uncaught exception 'RCTFatalException: Exception 'threading violation: expected the main thread' was thrown while invoking setEnabled on target Proximity with params (
    1
)', reason: 'Exception 'threading violation: expected the main thread' was thrown while ...'
*** First throw call stack:
(0x1a82c496c 0x1a7fdd028 0x1a81b414c 0x1008b3cb4 0x1008bba4c 0x1008c6454 0x1008c5b60 0x1016e5e1c 0x1016e727c 0x1016ee90c 0x1016ef4fc 0x1016fa4dc 0x1a7fcf6d0 0x1a7fd59e8)
libc++abi.dylib: terminating with uncaught exception of type NSException

Please let me know if i can fix it myself any help appreciated. thanks in advance

**Comment by sreekar89** [comment]
@slothstronaut please respond

**Comment by slothstronaut** [comment]
@sreekar89 I can't reproduce the issue. Clicking the eye is working as expected for me.

Can you possibly submit a PR with the updated SDK, I can test it out as long as it works I'll merge it in. Thanks

**Comment by theavijitsarkar** [comment]
[/Applications/MAMP/htdocs/XXX/src-cordova/platforms/ios/XX/Plugins/cordova-plugin-jitsi-meet/JitsiPlugin.mm:43] JitsiMeetViewDelegate CONFERENCE_JOINED {
    url = "https://meeting.forcepower.in/5e1468f49b18f86a1da82d40#config.startWithAudioMuted=false&config.startWithVideoMuted=false";
}
2020-05-12 22:19:54.327267+0530 XX[499:40579] [Process] kill() returned unexpected error 1
2020-05-12 22:19:54.329601+0530 XX[499:41607] *** Assertion failure in -[FBSSerialQueue assertOnQueue], /BuildRoot/Library/Caches/com.apple.xbs/Sources/FrontBoardServices/FrontBoard-626.4.1/FrontBoardServices/FBSSerialQueue.m:98
2020-05-12 22:19:54.330 [fatal][tid:com.facebook.react.ProximityQueue] Exception 'threading violation: expected the main thread' was thrown while invoking setEnabled on target Proximity with params (
    1
)
2020-05-12 22:19:54.332922+0530 XX[499:41607] Exception 'threading violation: expected the main thread' was thrown while invoking setEnabled on target Proximity with params (
    1
)
2020-05-12 22:19:54.333081+0530 XXp499:41607] *** Terminating app due to uncaught exception 'RCTFatalException: Exception 'threading violation: expected the main thread' was thrown while invoking setEnabled on target Proximity with params (
    1
)', reason: 'Exception 'threading violation: expected the main thread' was thrown while ...'
*** First throw call stack:
(0x18ef3aa48 0x18ec61fa4 0x18ee301c0 0x10523fcb4 0x105247a4c 0x105252454 0x105251b60 0x1060757fc 0x106076bd8 0x10607db48 0x10607e6e4 0x106089adc 0x18ec56b88 0x18ec59760)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by theavijitsarkar** [comment]
I am getting this on just launching the app

**Comment by theavijitsarkar** [comment]
@slothstronaut Thanks for the quick revert, A side question, when I connect my phone and do cordova build ios --device it works, else it does not builds. And I get this. Any ideas on how to fix this?

he following build commands failed:
	Ld /Users/av/Library/Developer/Xcode/DerivedData/Regular.li-doelncjsbarxwjbxovoukpfiwpuf/Build/Intermediates.noindex/Regular.li.build/Release-iphonesimulator/Regular.li.build/Objects-normal/x86_64/Binary/Regular.li normal x86_64
(1 failure)
xcodebuild: Command failed with exit code 65

**Comment by slothstronaut** [comment]
I was also having some trouble with this before the latest update, are you
able to get it work by manually running it in XCode?

Can you confirm what version of the plugin you have installed by running
`cordova plugin list`

You should see the following in the list as of (May 12, 2020):
`cordova-plugin-jitsi-meet 1.0.5 "JitsiPlugin"`

If not, may simply need to just grab the latest version. This most recent
update automatically embeds the frameworks correctly, previously you had to
manually include them. Not sure if thats the issue you are having above,
but seems like it could be related.

**Comment by theavijitsarkar** [comment]
Yes its updated to 1.0.5

```
com.pylonproducts.wifiwizard 0.2.11 "WifiWizard"
com.razorpay.cordova 0.16.1 "RazorpayCheckout"
cordova-background-geolocation 3.7.0-rc.2 "BackgroundGeolocation"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-android-wifi-manager 1.0.0 "Android WifiManager"
cordova-plugin-background-fetch 6.0.5 "CDVBackgroundFetch"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 4.1.1-dev "Camera"
cordova-plugin-chooser 1.3.1 "Chooser"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-cocoapod-support 1.6.2 "Cordova CocoaPods Dependency Support"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-email 1.2.7 "EmailComposer"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googleplayservices-check 1.0.0 "GooglePlayServicesCheck"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-jitsi-meet 1.0.5 "JitsiPlugin"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-uniquedeviceid 1.3.1 "UniqueDeviceID"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.5 "SocialSharing"
cordova.plugins.diagnostic 5.0.1 "Diagnostic"
es6-promise-plugin 4.1.0 "Promise"
phonegap-plugin-barcodescanner 8.1.0 "BarcodeScanner"
wifiwizard2 3.1.1 "WifiWizard2"
```

**Comment by theavijitsarkar** [comment]
@slothstronaut How difficult would it be to update the sdk? Is code rewriting required?

**Comment by slothstronaut** [comment]
Thanks for confirming.

Here are the list of plugins I'm using with it, so you can consider all of
these safe to use with the Jitsi plugin:

cordova-plugin-android-permissions 1.0.2 "Permissions"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-battery-status 1.2.5 "Battery"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-firebasex 7.0.2 "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-jitsi-meet 1.0.5 "JitsiPlugin"
cordova-plugin-media-capture 1.4.3 "Capture"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-purchase 9.0.0 "Purchase"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-vibration 2.1.6 "Vibration"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"

Any other plugins may potentially have an unknown conflict, I've witnessed
other conflicts between plugins, so unfortunately it is quite a common
thing.

If you can create a test build and remove any plugins not in this above
list, that will tell you if the problem is the plugin + your app, or a
conflict with another plugin you have installed.

**Comment by slothstronaut** [comment]
I'm not sure, to be frank, I am not an iOS developer, so I'm not the best
person to update it.

It may just be as simple as recompiling it, and updating the build
artifacts, but I'm just not well versed in it enough to know if thats a
small or large effort.

**Comment by theavijitsarkar** [comment]
@slothstronaut Could you guide me on how to update the ios, I guess you did it in the first time when creating this plugin

Check this comment, this is inevitable eventually.
https://github.com/jitsi/jitsi-meet/issues/6684

**Comment by slothstronaut** [comment]
@theavijitsarkar Actually, I'm not the one who originally created either plugin. 

Originally there were two main Cordova/Jitsi plugins on Android and iOS, but there was no plugin that was cross platform so I merged the plugins into one, made sure it worked and created documentation, thats all.

As for updating the iOS SDK, it seems you are more experienced with the subtle aspects and more specific Jitsi features, so I would guess you are more qualified to update the SDK :)

**Comment by theavijitsarkar** [comment]
I probably would have done it by now, if I knew. I downloaded the new sdk and replaced. Does not work.


```
55:47.351246+0530 Regular.li[2103:368538] Resetting plugins due to page load.
2020-05-13 17:55:51.164771+0530 XX.li[2103:368538] Finished load of: file:///private/var/containers/Bundle/Application/0D391D10-AC8C-4BA5-A2F8-4DAF6F23CE8B/XXX.li.app/www/index.html#/
2020-05-13 17:56:12.490545+0530 XXX[2103:368538] Received memory pressure event 1 vm pressure 0

Received memory pressure event 1 vm pressure 0
2020-05-13 17:57:22.163080+0530 XXX 2103:368941] [BoringSSL] boringssl_metrics_log_metric_block_invoke(131) Failed to log metrics
2020-05-13 17:57:22.163368+0530 XXX[2103:368941] [BoringSSL] boringssl_metrics_log_metric_block_invoke(133) Error Domain=NSOSStatusErrorDomain Code=-50 "Unsupported xpc type" UserInfo={NSDescription=Unsupported xpc type}
```

**Comment by theavijitsarkar** [comment]
This seems to work 
https://github.com/agorum/cordova-plugin-jitsi.git

Will test more

**Comment by slothstronaut** [comment]
Ok please keep me updated, if the SDK updates from that repo works I will
merge those changes back in. Our branches have diverged so it may be
manual, but it looks like he made some progress.

**Comment by sreekar89** [comment]
sorry for being away.
@theavijitsarkar  you saved my weekend. about to work on for updated sdk.
https://github.com/agorum/cordova-plugin-jitsi.git works great! 

@slothstronaut @theavijitsarkar  cheers :beers:

closing the issue.

**Comment by theavijitsarkar** [comment]
@sreekar89 Did it work in android? It messes up my gradle and I cant the android to compile

**Comment by slothstronaut** [comment]
Any details you can share on the gradle issues? What kind of errors are you
seeing after upgrading?

**Comment by theavijitsarkar** [comment]
I started getting the same issue with your plugin as well then added these to solve it

android.useAndroidX=true
android.enableJetifier=true

**Comment by theavijitsarkar** [comment]
@slothstronaut the other plugin worked, you can merge with it if you want.
